[project]
name = "vacant-lot-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "earthengine-api>=1.6.11",
    "google-api-python-client>=2.184.0",
    "google-auth>=2.41.1",
    "pydantic>=2.12.0",
    "pyyaml>=6.0.3",
]
